### ISSUE TITLE
Why are all emails and passwords sent to admin.vshosting.cloud?

### ISSUE THREAD

**Issue by rozza-m** [vshosting/dehydrated-clouddns#1]
Why are email adresses, client IDs and passwords sent to admin.vshosting.cloud and https://admin.vshosting.cloud/api/public/auth/login, **Not** straight to cloudns? **vshosting.cloud redirects to vshosting.cz, a third party that could be logging all email addresses and passwords used**.

**Comment by radek-sprta** [comment]
Hello,

I think there might be a misunderstanding. The plugin is for CloudDNS (a https://vshosting.cz service), not ClouDNS (https://www.cloudns.net/).
